#ifndef BASE_H
#define BASE_H
#include <iostream>
#include <vector>
#include <array>
#include <map>
#include <memory>
#include <string>
#include <optional>
#include <set>
#include <fstream>
#include <functional>
#include < unordered_map >

#include <mutex>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>

#include <vulkan/vulkan.h>

//#define mainNameSpace APPWORK

#endif // !BASE_H
